### ISSUE TITLE
`db:*` commands are not available

### ISSUE THREAD

**Issue by pqt** [alpas/starter#75]
Hey.

So I generated from this starter and am trying to perform migrations, however it appears that I do not have the commands for any of the `db:`prefixed operations and I'm not really sure why.

I know that Postgres wasn't supported properly like 9 months ago so I'm developing locally with MySQL incase that would've helped but haven't seen any update on whether or not that is still the case.

```
./alpas -v
0.16.2
```

```
./alpas db:migrate
Usage:  [OPTIONS] COMMAND [ARGS]...s]

Error: Got unexpected extra argument (db:migrate)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/Users/pqt/.sdkman/candidates/java/9.0.7-zulu/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
```

![](https://i.imgur.com/xkZ9IAz.png)

**Comment by armgitaar** [comment]
Hi @pqt  - 

Check `DatabaseConfig.kt` and make sure `addConnections(env)` is not commented out. The db commands under `./alpas help` display when a database connection is detected. 

https://alpas.dev/docs/database-getting-started#registering-database-connections

![image](https://user-images.githubusercontent.com/30202878/98305149-95882500-1f7e-11eb-8656-41cf1715b303.png)

**Comment by pqt** [comment]
Thank you @armgitaar ! That was exactly what the problem was. I totally missed that, assumed it was related to adding multiple connections (like registering a new one) rather than the actually adding of the db system.

Totally makes sense to me now though and I have migrations working as expected.

**Comment by armgitaar** [comment]
No worries, I'm glad you got it working now!
